[tool.poetry]
name = "spat"
version = "0.1.0"
description = ""
authors = ["tvi <tvi@sbtinstruments.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19"
scipy = "^1.5"
click = "^7.1.2"
altair = "^4.1.0"
altair-viewer = "^0.3.0"
vega-datasets = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
