[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pilus"
version = "0.1.0"
description = ""
authors = [
    { name = "tvi", email = "tvi@sbtinstruments.com" },
    { name = "fpa", email = "fpa@sbtinstruments.com" },
]
requires-python = ">=3.10,<4.0"
dependencies = [
    "immutables>=0.20,<1",
    "pydantic>=2.9.2,<3",
    "tinydb>=4.4.0,<5",
    "typeguard>=2.12.1,<3",
    "networkx>=3.4.2,<4",
    "python-magic>=0.4.27,<0.5",
]

[project.optional-dependencies]
cli = ["typer>=0.12.3,<0.13"]
polars = ["polars[pyarrow, numpy]>=1.3.0,<2"]

[project.scripts]
pilus = "pilus.cli:run"

[dependency-groups]
dev = [
    "pytest>=8.2.2,<9",
    "pyfakefs>=5.6.0,<6",
    "mypy>=1.10.1,<2",
    "pre-commit>=2.8.2,<3",
    "ruff>=0.5.2,<0.6",
]
